version: '2.1'

services:
  mysql_container:  # DataBase
    image: "percona:latest"
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./services_configs/mysql_config/mysql-init.sql:/data/application/mysql-init.sql
    command: --init-file /data/application/mysql-init.sql
    healthcheck:
      test: [ 'CMD', 'mysqladmin', '-uroot', '-ppass', 'ping', '-h', '127.0.0.1' ]
      timeout: 1s
      retries: 30

  mock_container:  # Mock VK_API
    image: "mock:latest"
    ports:
      - "5000:5000"
    volumes:
      - ./mock:/tmp/source_code
    entrypoint: /bin/bash /tmp/source_code/start_tests.sh
    healthcheck:
      test: curl --fail -s http://0.0.0.0:5000/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

  app:  # Application
    image: "myapp:latest"
    ports:
      - "8080:8080"
    volumes:
      - ./services_configs/app/app_config:/tmp/app_config
    entrypoint: /app/myapp --config=/tmp/app_config
    depends_on:
      mysql_container:
        condition: service_healthy
      mock_container:
        condition: service_healthy

#  tests: # Tests ORM SQL
#    build: ./source_code/
#    tty: true
#    volumes:
#      - ./source_code:/tmp/source_code
#    entrypoint: /bin/bash /tmp/source_code/start_tests.sh
#    depends_on:
#      mysql_container:
#        condition: service_healthy