- job:
    name: Test_MyApp_with_Jenkins
    description: "JJB Project, Pipeline\n"
    project-type: pipeline

    pipeline-scm:
      scm:
        - qa-python-scm
      script-path: "simple.groovy"

    wrappers:
      - timestamps
      - workspace-cleanup

    triggers:
      - pollscm:
          cron: '* * * * *'
